version: "3.9"

services:
  web:
    container_name: kyrius-next
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
